- name: example of string variable in playbook level
  hosts: webserver
  vars_files:
       - ./vars.yml    
  tasks:
    - name: install web service
      yum:
       name: "{{ websvc }}" 
       state: installed

    - name: start web service
      service:
        name: "{{ websvc }}"
        state: started
        enabled: true

    - name: create directory "{{ webroot }}"
      file:
        path: "{{ webroot }}"
        state: directory

    - name: create index.html
      copy:
        content: " hello"
        dest: "{{ webroot }}/index.html"

    - debug: 
        msg: "{{ websvc }} and {{ webroot }}"




